name: path_smoother
description: "Provides functionality to generate smooth paths from a list of points."
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
